// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject8;

internal sealed partial class Vsix
{
    public const string Id = "VSIXProject8.cf933215-27af-44ba-8696-7d7ba456437b";
    public const string Name = "VSIXProject8";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Tim Heuer";
    public const string Tags = "";
}
