// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject8;

using System;

/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
    public const string VSIXProject8String = "cbef2ab1-15c6-429c-a934-540d0c94e6f8";
    public static Guid VSIXProject8 = new Guid(VSIXProject8String);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
    public const int MyMenuGroup = 0x0001;
    public const int MyCommand = 0x0100;
}